### ISSUE TITLE
Balance incorrectly showing unspendable notification address amounts

### ISSUE THREAD

**Issue by maxtannahill** [cypherstack/stack_wallet#470]
BIP47 specifies that notification addresses should never be spent from, only spent to which is why dust amounts are used here as they serve no purpose to spend from.

Both Sparrow and Samourai do not include the balance of the notification address dust in the total balance displayed to the user.

**Comment by rehrar** [comment]
These are auto-frozen and hidden from the user. That said, I do not think it is wise to completely remove the ability to move this money around. Yes it's not advisable for privacy reasons, but that's why the option to do so is heavily hidden away behind many taps. But a user should still be able to do whatever they want with their funds.
